import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const akturaFont = localFont({
  src: "./fonts/Aktura-Regular.woff2",
});

const poppinsFont = localFont({
  src: "./fonts/Poppins-Regular.woff2",
});

const poppinsFontBold = localFont({
  src: "./fonts/Poppins-Bold.woff2",
});

const gambarinoFont = localFont({
  src: "./fonts/Gambarino-Regular.woff2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppinsFont.className}>{children}</body>
    </html>
  );
}
